name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_FRONTEND }} .
          docker push ${{ secrets.DOCKER_IMAGE_FRONTEND }}
      - name: Configure EKS Cluster
        uses: aws-actions/configure-eks-cluster@v1
        with:
          cluster-name: BasicUserRegistryFrontendEKS
          role-arn: ${{ secrets.EKS_IAM_ROLE_ARN }}
          kubeconfig: ${{ secrets.EKS_KUBECONFIG }}

      - name: Deploy to EKS
        uses: kubernetes/deploy@v2
        with:
          kubeconfig: ${{ secrets.EKS_KUBECONFIG }}
          deployment: userregfrontenddeploy
          container: userregfrontendcontainer
          image: ${{ secrets.DOCKER_IMAGE_FRONTEND }}
      # - name: Deploy to EKS
      #   uses: aws-eks/deploy@v1
      #   with:
      #     cluster-name: BasicUserRegistryFrontendEKS
      #     role-arn: ${{ secrets.EKS_IAM_ROLE_ARN }}
      #     kubeconfig: ${{ secrets.EKS_KUBECONFIG }}
      #     deployment: userregfrontenddeploy
      #     container: userregfrontendcontainer
      #     image: ${{ secrets.DOCKER_IMAGE_FRONTEND }}
      # - name: Deploy to Kubernetes
      #   uses: kubernetes/deploy@v2
      #   with:
      #     kubeconfig: ${{ secrets.KUBECONFIG }}
      #     deployment: my-app-frontend
      #     container: my-app-frontend
      #     image: ${{ secrets.DOCKER_IMAGE_FRONTEND }}