name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy to EKS
        env:
          AWS_DEFAULT_REGION: ap-southeast-1
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBECONFIG" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          kubectl --kubeconfig=$(pwd)/kubeconfig apply -f deployment.yaml --validate=false
          kubectl --kubeconfig=$(pwd)/kubeconfig rollout status deployment/userregfrontenddeploy