name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_FRONTEND }} .
          docker push ${{ secrets.DOCKER_IMAGE_FRONTEND }}
      - name: Setup AWS Credentials
        uses: aws-actions/setup-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Deploy to EKS
        uses: kubernetes/deploy@v2
        with:
          kubeconfig: ${{ secrets.EKS_KUBECONFIG }}
          deployment: userregfrontenddeploy
          container: userregfrontendcontainer
          image: ${{ secrets.DOCKER_IMAGE_FRONTEND }}